DROP DATABASE IF EXISTS pastebin;
CREATE DATABASE pastebin;
USE pastebin;

CREATE TABLE posts (
  id VARCHAR(128),
  author VARCHAR(128),
  text LONGTEXT NOT NULL,
  type VARCHAR(128) NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY (id)
);